service: taxdown-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev
  environment:
    NODE_ENV: ${env:NODE_ENV}
    MONGO_DB_NAME: ${env:MONGO_DB_NAME}
    MONGO_URI: ${env:MONGO_URI}

functions:
  app:
    handler: dist/handler.main
    events:
      - httpApi:
          path: /{proxy+}
          method: any

plugins:
  - serverless-offline
