name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      MONGO_DB_NAME: taxdown
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run tests (with coverage)
        run: npm test
